package com.mdau.momentspackagingbackendjavafirstclient.order.entity;

import com.mdau.momentspackagingbackendjavafirstclient.user.entity.User;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "orders", indexes = {
        @Index(name = "idx_orders_reference",       columnList = "reference",       unique = true),
        @Index(name = "idx_orders_customer_id",     columnList = "customer_id"),
        @Index(name = "idx_orders_status",          columnList = "status"),
        @Index(name = "idx_orders_created_at",      columnList = "created_at"),
        @Index(name = "idx_orders_payment_status",  columnList = "payment_status"),
        @Index(name = "idx_orders_email",           columnList = "email"),
        @Index(name = "idx_orders_idempotency_key", columnList = "idempotency_key", unique = true)
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, unique = true, length = 30)
    private String reference;

    /**
     * This business's own internal sequential invoice number (e.g.
     * MP-INV-2026-000123) — null until payment is confirmed, since an
     * unpaid/cancelled order should never consume an invoice number.
     * Generated by InvoiceNumberGenerator in PaymentService. Not a
     * KRA-issued eTIMS invoice number — see the invoice PDF's disclaimer.
     */
    @Column(name = "invoice_number", unique = true, length = 30)
    private String invoiceNumber;

    /** Set alongside invoiceNumber, when payment was actually confirmed. */
    @Column(name = "paid_at")
    private Instant paidAt;

    @Column(name = "idempotency_key", unique = true, length = 64)
    private String idempotencyKey;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    private User customer;

    @Column(name = "contact_name", nullable = false, length = 255)
    private String contactName;

    @Column(nullable = false, length = 255)
    private String email;

    @Column(nullable = false, length = 30)
    private String phone;

    @Column(name = "delivery_address", columnDefinition = "TEXT")
    private String deliveryAddress;

    @Column(length = 100)
    private String city;

    @Column(length = 100)
    private String county;

    @Column(name = "postal_code", length = 20)
    private String postalCode;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private OrderStatus status = OrderStatus.PENDING_PAYMENT;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false, length = 30)
    private PaymentMethod paymentMethod;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 20)
    @Builder.Default
    private PaymentStatus paymentStatus = PaymentStatus.PENDING;

    @Enumerated(EnumType.STRING)
    @Column(name = "fulfillment_type", nullable = false, length = 30)
    @Builder.Default
    private FulfillmentType fulfillmentType = FulfillmentType.ZONE_DELIVERY;

    // Ã¢â€â‚¬Ã¢â€â‚¬ OWN_COURIER fields Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬

    @Enumerated(EnumType.STRING)
    @Column(name = "courier_type", length = 30)
    private CourierType courierType;

    @Column(name = "courier_service_name", length = 255)
    private String courierServiceName;

    @Column(name = "courier_stage_or_office", length = 500)
    private String courierStageOrOffice;

    // Ã¢â€â‚¬Ã¢â€â‚¬ Dispatcher fields Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬

    /**
     * Set to true by dispatcher after ticking all items in the checklist.
     * Required before DISPATCHED status can be set.
     */
    @Column(name = "contents_verified", nullable = false)
    @Builder.Default
    private Boolean contentsVerified = false;

    @Enumerated(EnumType.STRING)
    @Column(name = "delivery_confirmation_status", length = 30)
    private DeliveryConfirmationStatus deliveryConfirmationStatus;

    // Ã¢â€â‚¬Ã¢â€â‚¬ Financials Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬Ã¢â€â‚¬

    @Column(precision = 12, scale = 2, nullable = false)
    private BigDecimal subtotal;

    /**
     * VAT-inclusive sum of line totals for non-vat-exempt items only
     * (already embedded in subtotal, not additional to it).
     */
    @Column(name = "taxable_amount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal taxableAmount = BigDecimal.ZERO;

    /**
     * VAT extracted from each non-exempt line's VAT-inclusive price, using
     * that product's own vatRate at the time the order was placed. Computed
     * in CheckoutService.checkout() — already embedded in subtotal/total,
     * not additional to them.
     */
    @Column(name = "vat_amount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal vatAmount = BigDecimal.ZERO;

    @Column(name = "delivery_fee", precision = 12, scale = 2, nullable = false)
    @Builder.Default
    private BigDecimal deliveryFee = BigDecimal.ZERO;

    @Column(precision = 12, scale = 2, nullable = false)
    @Builder.Default
    private BigDecimal discount = BigDecimal.ZERO;

    @Column(name = "total_amount", precision = 12, scale = 2, nullable = false)
    private BigDecimal totalAmount;

    @Column(columnDefinition = "TEXT")
    private String notes;

    @Column(name = "staff_notes", columnDefinition = "TEXT")
    private String staffNotes;

    @Column(name = "assigned_to", length = 255)
    private String assignedTo;

    @Column(name = "assigned_to_id")
    private UUID assignedToId;

    @Column(name = "promo_code", length = 50)
    private String promoCode;

    /** Customer ticked "I need a tax invoice / VAT document" at checkout. See TaxDocument. */
    @Column(name = "tax_invoice_requested", nullable = false)
    @Builder.Default
    private Boolean taxInvoiceRequested = false;

    @Column(name = "tax_invoice_email", length = 255)
    private String taxInvoiceEmail;

    /** Customer's own KRA PIN (distinct from business.kraPin, which is Moments' seller PIN), printed on the tax invoice. */
    @Column(name = "tax_invoice_kra_pin", length = 20)
    private String taxInvoiceKraPin;

    /**
     * Refund handling is deliberately NOT automated: logging a request here never touches
     * status/paymentStatus/inventory by itself. An admin reviews it and, separately, decides
     * whether to move the order to REFUNDED (manual override), mark the payment record failed,
     * and/or restore stock — each its own explicit action. See OrderService.requestRefund /
     * markPaymentFailed / restoreInventory / resolveRefundRequest.
     */
    @Column(name = "refund_requested_at")
    private Instant refundRequestedAt;

    @Column(name = "refund_request_reason", columnDefinition = "TEXT")
    private String refundRequestReason;

    @Column(name = "refund_requested_by", length = 255)
    private String refundRequestedBy;

    @Column(name = "refund_resolved_at")
    private Instant refundResolvedAt;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<OrderItem> items = new ArrayList<>();

    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<OrderStatusHistory> statusHistory = new ArrayList<>();

    @PrePersist
    void prePersist() {
        this.createdAt = Instant.now();
        this.updatedAt = Instant.now();
    }

    @PreUpdate
    void preUpdate() {
        this.updatedAt = Instant.now();
    }
}